[T5OP-1] base setup for react-boiler-plate
tookitaki/legendary-fortnight pull request #1
Opened 2021-05-06 03:56 UTC by anishkr07

2021-05-06 11:37 UTC, KostyaTookitaki reviewed
great! I left some comments which we can discuss, don't be afraid that there are so many of them, maybe most of them are not relevant, will see :))) anyways I am open to discussion about each of them... thanks!

2021-05-06 11:37 UTC, KostyaTookitaki commented on src/sagas/tests/index.spec.js
> +import { all, fork } from "@redux-saga/core/effects";
please rename folder to be `__tests__`

2021-05-06 11:37 UTC, KostyaTookitaki commented on src/utils/TokenHandler.js
> +// export default tokenHandler;
why is that commented out? if not needed lets just remove it, but don't forget to rename the file as well

2021-05-06 11:37 UTC, KostyaTookitaki commented on src/utils/appConfig.js
> +        // eslint-disable-next-line
why `eslint-disable-next-line` is needed here?

2021-05-06 11:37 UTC, KostyaTookitaki commented on src/utils/appConfig.js
> +    // API_URL : 'http://52.7.32.121:7080/api/rs/v1'
in order to avoid doing this in the code we need to start using `.env` file in order to toggle between different URLs for different envs. Those variables will be available by accessing `process.env` https://create-react-app.dev/docs/adding-custom-environment-variables/

2021-05-06 11:37 UTC, KostyaTookitaki commented on src/utils/utils.js
> +export const isNotNullUndefined = val => [isNotNull, isNotUndefined].every(x => x(val));
all those are available in `lodash`: `isNull`, `isNil`, `isUndefined`

2021-05-06 11:37 UTC, KostyaTookitaki commented on src/utils/tests/path.spec.js
> +    });
wow, never seen such before :) interesting... actually your test does not use `realtivePath` variable at all 🤔 does this work at all? 😄

2021-05-07 00:29 UTC, anishkr07 commented on .editorconfig
> +trim_trailing_whitespace = true
done

2021-05-07 00:31 UTC, anishkr07 commented on package.json
> +  "main": "index.js",
fixed

2021-05-07 00:31 UTC, anishkr07 commented on package.json
> +    "update-snapshot": "NODE_ENV=test jest --u",
fixed

2021-05-07 00:32 UTC, anishkr07 commented on package.json
>    "eslintConfig": {
removed .eslintrc

2021-05-07 00:37 UTC, anishkr07 commented on package.json
> +  "dependencies": {
added npm install --save typescript @types/node @types/react @types/react-dom @types/jest
note : @types/jest is also in dependencies and not devDevpendenicies. should it be ?

2021-05-07 00:47 UTC, anishkr07 commented on package.json
> +    "@ant-design/icons": "^4.6.2",
addedd @fortawesome/react-fontawesome , @fortawesome/fontawesome-svg-core

2021-05-07 00:49 UTC, anishkr07 commented on package.json
> +    "axios": "^0.21.1",
which one react-lodash or loadash ?

2021-05-07 00:50 UTC, anishkr07 commented on package.json
> +    "styled-components": "^5.2.3",
added

2021-05-07 00:53 UTC, anishkr07 commented on package.json
> +    "@testing-library/react": "^11.2.6",
added

2021-05-07 00:58 UTC, anishkr07 commented on package.json
> +    "jest-dom": "^4.0.0",
removed

2021-05-07 01:09 UTC, anishkr07 commented on package.json
> +      "git add"
I am not sure on this , if it does

2021-05-07 01:10 UTC, anishkr07 commented on package.json
> +      "eslint --fix",
discuss

2021-05-07 01:14 UTC, anishkr07 commented on public/index.html
>        name="description"
Good point , added back

2021-05-07 01:16 UTC, anishkr07 commented on public/index.html
> +    <!-- <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" /> -->
Some of the code is till , as its sort of instruction

2021-05-07 01:16 UTC, anishkr07 commented on src/actions/actionsUtil.js
> +export default function actionCreator(type, ...argNames) {
discuss

2021-05-07 01:23 UTC, anishkr07 commented on src/actions/login.js
> +export const loginUser = actionCreator(LOGIN_USER, 'token');
fixed

2021-05-07 01:25 UTC, anishkr07 commented on src/actions/tests/login.spec.js
> +import {
fixed

2021-05-07 01:26 UTC, anishkr07 commented on src/actions/tests/login.spec.js
> +        expect(actual).toEqual(expected);
discuss

2021-05-07 01:29 UTC, anishkr07 commented on src/components/Dashboard.jsx
> +            <Heading isHeading={true}>Hello World</Heading>
this is just a dummy one , removed true

2021-05-07 01:30 UTC, anishkr07 commented on src/components/ErrorBoundaryWrapper.jsx
> +import paths from '../utils/path';
discuss

2021-05-07 01:34 UTC, anishkr07 commented on src/components/ErrorBoundaryWrapper.jsx
> +    return <>{hasError ? this.renderErrorPage() : children}</>;
static getDerivedStateFromError() {
    return { hasError: true };
  }
getDerivedStateFromError : also sets hasError to true , so we may have to add history.push(paths.error) at multiple places
lets discuss

2021-05-07 01:41 UTC, anishkr07 commented on src/components/Login.jsx
> +      ...this.state,
removed

2021-05-07 01:41 UTC, anishkr07 commented on src/components/Login.jsx
> +      ...this.state,
removed

2021-05-07 01:43 UTC, anishkr07 commented on src/components/Login.jsx
> +            error.message ? error.message : String(error)}</Text>)
yes, these are dummy codes , 
fixed

2021-05-07 01:52 UTC, anishkr07 commented on src/components/NotFoundPage.js
> +  const style = {
dummy component

2021-05-07 01:53 UTC, anishkr07 commented on src/index.js
> +        <GlobalStyle />
discuss

2021-05-07 01:56 UTC, anishkr07 commented on src/index.js
> -// If you want to start measuring performance in your app, pass a function
added back

2021-05-07 01:57 UTC, anishkr07 commented on src/reducers/reducersUtil.js
> +export default function createReducer(initialState, handlers) {
this is specific to reducers , so i thought its better to put it there

2021-05-07 01:57 UTC, anishkr07 commented on src/reducers/tests/index.spec.js
> +import { createStore } from 'redux';
done

2021-05-07 01:58 UTC, anishkr07 commented on src/reducers/tests/index.spec.js
> +    const store = createStore(appReducer);
discuss

2021-05-07 01:58 UTC, anishkr07 commented on src/sagas/tests/index.spec.js
> +import { all, fork } from "@redux-saga/core/effects";
fixed

2021-05-07 01:58 UTC, anishkr07 commented on src/utils/TokenHandler.js
> +// export default tokenHandler;
working on it

2021-05-07 01:59 UTC, anishkr07 commented on src/utils/appConfig.js
> +        // eslint-disable-next-line
sometimes, it crosses character limit of 80 per line

2021-05-07 02:00 UTC, anishkr07 commented on src/utils/tests/path.spec.js
> +    });
it works , may need to remove the unused variable

2021-05-07 02:01 UTC, anishkr07 commented on src/utils/utils.js
> +export const isNotNullUndefined = val => [isNotNull, isNotUndefined].every(x => x(val));
added loadash

2021-05-07 02:51 UTC, anishkr07 commented on .editorconfig
> +trim_trailing_whitespace = true
added

2021-05-07 02:52 UTC, anishkr07 commented on .eslintrc
> +    "parser": "babel-eslint",
fixed

2021-05-07 03:11 UTC, anishkr07 commented on package.json
> +    "axios": "^0.21.1",
added loadash

2021-05-07 03:18 UTC, anishkr07 commented on package.json
> +    "eslint-plugin-react-hooks": "^4.2.0",
done

2021-05-07 03:19 UTC, anishkr07 commented on package.json
> +      "git add"
removed

2021-05-07 04:54 UTC, anishkr07 commented on src/reducers/tests/index.spec.js
> +    const store = createStore(appReducer);
fixed

2021-05-11 03:31 UTC, anishkr07 commented on package.json
> +    "@testing-library/user-event": "^12.8.3",
done

2021-05-11 11:12 UTC, KostyaTookitaki commented on src/index.js
> -// If you want to start measuring performance in your app, pass a function
you added back different comment about service worker, should be about `reportWebVitals`

2021-05-11 11:34 UTC, KostyaTookitaki commented on src/utils/path.js
> +const paths = {
In fact I think this constant should be in `/constants` folder and its name should be uppercased like `PATHS` since it is a static constant

2021-05-11 11:36 UTC, KostyaTookitaki commented on src/utils/utils.js
> +export const isNotNullUndefined = (val) =>
isn't it easier to use `isNil` from lodash? I think I mentioned it before...

2021-05-11 11:39 UTC, KostyaTookitaki commented on src/components/Loading.js
> +import { Spin } from 'antd';
some of your component files has `.js` extendion, but some `.jsx`, lets have a convention and to use `.js` always for sake of simplicity, how does it sound to you? It should not affect anything

2021-05-12 03:09 UTC, KostyaTookitaki commented on package.json
>    "eslintConfig": {
I think it would be great to limit file size so developers will not write big components like it is now, which is hardy maintainable... I think 300 lines will do it

in order to do that please put such `eslintConfig`:

```
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ],
    "rules": {
      "max-lines": [
        "error",
        300
      ]
    }
  },
```

2021-05-16 14:58 UTC, anishkr07 commented on package.json
> +    "format": "prettier ./src/**/*.{js,jsx,css,html,md,json,spec.jsx,spec.js} --config .prettierrc --write",
done

2021-05-16 14:58 UTC, anishkr07 commented on package.json
>    "eslintConfig": {
done

2021-05-16 15:33 UTC, anishkr07 commented on src/sagas/login.js
> +    // yield put(logoutUser());
I am not sure , it came fro merge, i am removing the comment

2021-05-17 06:14 UTC, KostyaTookitaki reviewed
just a comment to drop review request since not all items covered

2021-05-18 03:23 UTC, KostyaTookitaki requested changes
cool! every iteration it is getting much better :) we could finish review earlier but for some reason you are missing some of my comments... :(
please ping me if you need any clarification. Also if you have time pressure or something I think we can use help of @sinisbad123 for fixing some comments

2021-05-18 03:23 UTC, KostyaTookitaki commented on src/routes/Routes.js
> +        if (isAuthenticated()) {
for some reason in the `<Dashboard>` component you have totally different way how to check if user is logged in or not, why is so?

2021-05-18 03:23 UTC, KostyaTookitaki commented on src/routes/Routes.js
> +          return <Redirect to="/" />;
please use you paths constant

2021-05-18 03:23 UTC, KostyaTookitaki commented on src/sagas/login.js
> +      authResponse.data.token
?

2021-05-18 03:23 UTC, KostyaTookitaki commented on src/theme/GlobalStyle.js
> +`;
not sure what does this `GlobalStyle` do at all... can you elaborate?

2021-05-18 03:23 UTC, KostyaTookitaki commented on src/theme/Theme.js
> +import themeAttributes from './themeAttributes';
kudos for extracting this in separate file

2021-05-18 03:23 UTC, KostyaTookitaki commented on src/theme/themeAttributes.js
> +  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
great that we have styled-system theme preparation, but I haven't seen any usage of it yet, we need to have it in use.

2021-05-18 03:23 UTC, KostyaTookitaki commented on src/utils/path.js
> +const paths = {
?

2021-05-18 03:38 UTC, anishkr07 commented on src/components/ErrorBoundaryWrapper.jsx
> +  }
it was part of official docs : https://reactjs.org/docs/react-component.html#componentdidcatch
yes, but it makes sense to remove it

2021-05-18 03:39 UTC, anishkr07 commented on src/components/Loading.jsx
> +      {' '}
removed

2021-05-18 03:41 UTC, anishkr07 commented on src/components/Login.jsx
> +  dispatchLoginUser: (payload) => loginUser(payload)
done

2021-05-18 03:41 UTC, anishkr07 commented on src/components/Logout.jsx
> +  dispatchLogoutUser: () => logoutUser()
done

2021-05-18 03:42 UTC, anishkr07 commented on src/components/NotFoundPage.jsx
> +      <Link to="/"> Go back to homepage </Link>
done

2021-05-18 03:43 UTC, anishkr07 commented on src/components/__tests__/Login.spec.js
> +    Object.defineProperty(window, 'matchMedia', {
Right now , it may not be required , as Logout component will not be rendered  at multiple places

2021-05-18 03:45 UTC, anishkr07 commented on src/components/__tests__/Logout.spec.js
> +  it('should call login on click of LOGIN button', () => {
done

2021-05-18 03:46 UTC, anishkr07 commented on src/reducers/__tests__/login.spec.js
> +    });
if possible , lets go with this now. Time constraint

2021-05-18 03:48 UTC, anishkr07 commented on src/routes/Routes.js
> +const PrivateRoute = ({ component: Component, ...rest }) => (
Private Route is still small enough , we will be implementing layout over it , so it may be fine to leave for now.

2021-05-18 03:49 UTC, anishkr07 commented on src/routes/Routes.js
> +          return <Redirect to="/" />;
done

2021-05-18 03:50 UTC, anishkr07 commented on src/sagas/login.js
> +      authResponse.data.token
discuss

2021-05-18 03:50 UTC, anishkr07 commented on src/theme/GlobalStyle.js
> +`;
Even i forgot now , lets discuss

2021-05-18 03:52 UTC, anishkr07 commented on src/utils/path.js
> +const paths = {
discuss

2021-05-18 03:59 UTC, anishkr07 commented on src/routes/Routes.js
> +        if (isAuthenticated()) {
I think this cam from merge , @sinisbad123  ?
We may remove it, Marcus ??

2021-05-18 04:09 UTC, vkbalakrishnan commented on src/sagas/login.js
> +      authResponse.data.token
We may need to add the babel proposal plugin to webpack. You can see the implementation in product-amls/fe

2021-05-18 07:30 UTC, KostyaTookitaki commented on src/reducers/__tests__/login.spec.js
> +    });
ok

2021-05-18 07:33 UTC, KostyaTookitaki commented on src/sagas/login.js
> +      authResponse.data.token
this should already supported by create-react-app without any additional configuration, we can simply try to validate

2021-05-18 08:45 UTC, KostyaTookitaki commented on package.json
> +    "pre-commit": "lint-staged",
not sure how it was working for you but you missed one script which is required by husky to work, please add it:

```
    "prepare": "husky install",
```

because of luck of this PR from Marcus was not auto-formatted, so please make sure to format all files which come from his PR https://github.com/tookitaki/legendary-fortnight/pull/6/files

2021-05-19 02:39 UTC, anishkr07 commented on src/components/Login.jsx
> +      <div style={{ width: '100%' }}>
done

2021-05-19 02:59 UTC, anishkr07 commented on src/components/__tests__/Login.spec.js
> +    history.push = jest.fn();
done

2021-05-20 06:59 UTC, KostyaTookitaki requested changes
very minor comments, you should be able to fix them quickly and then we can merge

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/components/AppLayout.jsx
> +const SideBar = styled(Sider)`
it would be great to place styled components under component itself, so reader will first see logical part and only then styles

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/components/ErrorBoundaryWrapper.jsx
> +    return <>{children}</>;
i think you can simply return `children`

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/components/Loading.jsx
> +  color: '#3F516F';
not sure but looks like this color style is not working since there are quotes around color code

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/components/Loading.jsx
> +const Div = styled.div`
do you really need this wrapper? I think you can style `Spin` like `styled(Spin)`

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/components/Login.jsx
> +      <div style={{ width: '100%' }}>
style object is still here, please convert to styled component. Please check other styles in this file

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/components/Logout.jsx
> +  loading: PropTypes.bool
you forgot to mention `history` in prop types

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/components/Logout.jsx
> +const mapDispatchToProps2 = {
strangely this has suffix `...2` :)

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/components/NotFoundPage.jsx
> +import paths from '../constants/path';
as I mentioned before this such static constants better to be uppercased like `PATHS`

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/components/NotFoundPage.jsx
> +  color: '#31394D';
does this really work when having quotes? I see such second time...

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/utils/setupTests.js
> +  Object.defineProperty(window, 'matchMedia', {
I meant to put this code to be run in `src/setupTests.js`

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/routes/Routes.js
> +          return <Redirect to="/" />;
not done

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/routes/Routes.js
> +        if (isAuthenticated()) {
?

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/constants/path.js
> +const paths = {
please make it upper cased

2021-05-20 06:59 UTC, KostyaTookitaki commented on src/components/__tests__/Login.spec.js
> +    history.push.mockClear();
you should use `.mockRestore()` to restore initial implementation of `history.push`

2021-05-21 08:54 UTC, KostyaTookitaki approved these changes

2021-05-21 09:39 UTC, merged